
export const ASSETS = {
  img_player_front_right: "https://i.ibb.co/S4YhXH19/player-front-right.png",
  img_player_back_right: "https://i.ibb.co/SwVp44h3/player-back-right.png",
  img_armor1: "https://i.ibb.co/XZ7ZdVg3/e-armor1.png",
  img_armor2: "https://i.ibb.co/TB9Qdhkf/e-armor2.png",
  img_armor3: "https://i.ibb.co/N2dCNwFt/e-armor3.png",
  img_basic: "https://i.ibb.co/BVZB77Jg/e-basic.png",
  img_critter: "https://i.ibb.co/ksBnxyFH/e-critter.png",
  img_fast: "https://i.ibb.co/VcMYbKjp/e-fast.png",
  img_giant: "https://i.ibb.co/23cV4ct6/e-giant.png",
  img_shooting: "https://i.ibb.co/d47j3DPF/e-shooting.png",
  img_swarm_center: "https://i.ibb.co/MyKZDBGY/e-swarm-center.png",

  // Character-Specific NPC Assets
  img_npc_tutorial_front: "https://i.ibb.co/4gVc5ryz/npc-tutorial-front-right.png",
  img_npc_tutorial_back: "https://i.ibb.co/4gVc5ryz/npc-tutorial-front-right.png",
  img_npc_lily_front: "https://i.ibb.co/DSfz04t/npc-lily-back-right.png",
  img_npc_lily_back: "https://i.ibb.co/DSfz04t/npc-lily-back-right.png",
  img_npc_jelly_front: "https://i.ibb.co/Lz9qd9RQ/npc-jelly-front-right.png",
  img_npc_jelly_back: "https://i.ibb.co/3YTFkXbQ/npc-jelly-back-right.png",
  img_npc_farmer_front: "https://i.ibb.co/WNmK5HD9/npc-farmer-back-right.png",
  img_npc_farmer_back: "https://i.ibb.co/WNmK5HD9/npc-farmer-back-right.png",
  img_npc_sourgrape_front: "https://i.ibb.co/QFv31tXV/npc-sourgrape-back-right.png",
  img_npc_sourgrape_back: "https://i.ibb.co/QFv31tXV/npc-sourgrape-back-right.png",
  img_npc_shroom_front: "https://i.ibb.co/Wpk01YZ1/npc-shroom-back-right.png",
  img_npc_shroom_back: "https://i.ibb.co/Wpk01YZ1/npc-shroom-back-right.png",
  img_npc_knight_front: "https://i.ibb.co/mVhgsTC7/npc-knight-font-right.png",
  img_npc_knight_back: "https://i.ibb.co/y2XGN8P/npc-knight-back-right.png",
  img_npc_hunter_front: "https://i.ibb.co/8nbF6xhC/npc-hunter-front-right.png",
  img_npc_hunter_back: "https://i.ibb.co/mrQ6tqBr/npc-hunter-back-right.png",
  img_npc_shadie_front: "https://i.ibb.co/60xMRvtS/npc-shadie-front-right.png",
  img_npc_shadie_back: "https://i.ibb.co/DPkfj7Mz/npc-shadie-back-right.png",

  // Legacy NPC Template (Fallback)
  img_npc_template_front: "https://i.ibb.co/yF5JThHT/npc-template-front-right.png",
  img_npc_template_back: "https://i.ibb.co/Z17bPCMW/npc-template-back-right.png",

  // Turret Assets
  img_t_firepea_front: "https://i.ibb.co/Zz2k7PCM/t-firepea-front-right.png",
  img_t_firepea_back: "https://i.ibb.co/5W4MMrxX/t-firepea-back-right.png",
  img_t_iceray_front: "https://i.ibb.co/JW2kYjJH/t-iceray-front-right.png",
  img_t_iceray_back: "https://i.ibb.co/xqJ9y2Cm/t-iceray-back-right.png",
  img_t_laser_front: "https://i.ibb.co/ccs9YWvw/t-laser-front-right.png",
  img_t_laser_back: "https://i.ibb.co/39SS0YBD/t-laser-back-right.png",
  img_t_laser2_front: "https://i.ibb.co/1fxVpc8H/t-laser2-front-right.png",
  img_t_laser2_back: "https://i.ibb.co/4RPyMPy7/t-laser2-back-right.png",
  img_t_laserexplode_front: "https://i.ibb.co/rK0052X4/t-laserexplode-front-right.png",
  img_t_laserexplode_back: "https://i.ibb.co/SDMRm4c9/t-laserexplode-back-right.png",
  img_t_mortar_front: "https://i.ibb.co/p63TyK8L/t-mortar-front-right.png",
  img_t_mortar_back: "https://i.ibb.co/svdMBgmP/t-mortar-back-right.png",
  img_t_pea_front: "https://i.ibb.co/kV7yRYjR/t-pea-front-right.png",
  img_t_pea_back: "https://i.ibb.co/sJ10NYNV/t-pea-back-right.png",
  img_t_peanut_front: "https://i.ibb.co/V0y5TJyH/t-peanut-front-right.png",
  img_t_peanut_back: "https://i.ibb.co/vCQcPgvH/t-peanut-back-right.png",
  img_t_puncher_front: "https://i.ibb.co/0jG5Ckj6/t-puncher-front-right.png",
  img_t_puncher_back: "https://i.ibb.co/F4xzmLXH/t-puncher-back-right.png",
  img_t_repeater_front: "https://i.ibb.co/7tY0xmZC/t-repeater-front-right.png",
  img_t_repeater_back: "https://i.ibb.co/9HVk6j7f/t-repeater-back-right.png",
  img_t_snowpea_front: "https://i.ibb.co/LdXZHJmY/t-snowpea-front-right.png",
  img_t_snowpea_back: "https://i.ibb.co/LzxCPC3D/t-snowpea-back-right.png",
  img_t_sunflower_front: "https://i.ibb.co/m5ycbXKr/t-sunflower-front-right.png",
  img_t_lilypad_front: "https://i.ibb.co/LXsjh9Q0/t-lilypad.png",

  // Special Turrets
  img_t0_puffshroom_back: "https://i.ibb.co/VGYhBp3/t-puffshroom-back-right.png",
  img_t0_puffshroom_front: "https://i.ibb.co/yn00YBFP/t-puffshroom-front-right.png",
  img_t0_grapeshot_back: "https://i.ibb.co/8g8tH2Zy/t-grapeshot-back-right.png",
  img_t0_grapeshot_front: "https://i.ibb.co/Jw6Lm46D/t-grapeshot-front-right.png",
  img_t0_jalapeno_front: "https://i.ibb.co/kgvP3ZrD/t-jalapeno-front-right.png",
  img_t0_firecherry_front: "https://i.ibb.co/h1LjfXPS/t-firecherry-front-right.png",
  img_t0_starfruit_front: "https://i.ibb.co/sXWz0n3/t-starfruit-front-right.png",
  img_t0_iceshroom_front: "https://i.ibb.co/sdShyXN8/t-iceshroom-front-right.png",
  img_t0_cherrybomb_front: "https://i.ibb.co/PzgRmRmL/t-cherrybomb-front-right.png",
  img_seed_stray_t2: "https://i.ibb.co/gb0CSBYs/seed-stray-t2.png",

  // Tier 3 Assets
  img_t_triplepea_front: "https://i.ibb.co/xtrcv6Sp/t-tripea-front-right.png",
  img_t_triplepea_back: "https://i.ibb.co/7dZFZh4n/t-tripea-back-right.png",
  img_t_firepea2_front: "https://i.ibb.co/wZpMCD9x/t-firepea2-front-right.png",
  img_t_firepea2_back: "https://i.ibb.co/vgPLkkX/t-firepea2-back-right.png",
  img_t_spinnut_front: "https://i.ibb.co/6cvtzJ1f/t-spinnut-front-right.png",
  img_t_spinnut_back: "https://i.ibb.co/j96zfqNc/t-spinnut-back-right.png",
  img_t_mortar2_front: "https://i.ibb.co/cSnHsYz9/t-mortar2-front-right.png",
  img_t_mortar2_back: "https://i.ibb.co/VRz9Wpc/t-mortar2-back-right.png",
  img_t_snowpea2_front: "https://i.ibb.co/KpwqrMfX/t-snowpea2-front-right.png",
  img_t_snowpea2_back: "https://i.ibb.co/s94WvdCG/t-snowpea2-back-right.png",
  img_t_inferno_front: "https://i.ibb.co/PZwZPcVr/t-inferno-front-right.png",
  img_t_inferno_back: "https://i.ibb.co/0p2BRPNx/t-inferno-back-right.png",
  img_t_flamethrower_front: "https://i.ibb.co/v6ZrJ9yH/t-flamethrower-back-right.png",
  img_t_flamethrower_back: "https://i.ibb.co/v6ZrJ9yH/t-flamethrower-back-right.png",
  img_t_bowling_front: "https://i.ibb.co/N6VpwCqr/t-bowling-front-right.png",
  img_t_bowling_back: "https://i.ibb.co/HyWxj89/t-bowling-back-right.png",
  img_t_repulser_front: "https://i.ibb.co/GvPf6tVZ/t-repulser-front-right.png",
  img_t_snowpeanut_front: "https://i.ibb.co/WpvXnSQF/t-snowpeanut-front-right.png",
  img_t_snowpeanut_back: "https://i.ibb.co/pjDzbZx9/t-snowpeanut-back-right.png",
  img_t_skymortar_front: "https://i.ibb.co/3VtsPmw/t-skymortar-front-right.png",
  img_t_laser3_front: "https://i.ibb.co/nMkVfHm1/t-laser3-front-right.png",
  img_t_laser3_back: "https://i.ibb.co/20wwWTpY/t-laser3-back-right.png",
  img_t_puncher2_front: "https://i.ibb.co/9HJZQm20/t-puncher2-front-right.png",
  img_t_puncher2_back: "https://i.ibb.co/bjc3Km30/t-puncher2-back-right.png",
  img_t_aoelaser_front: "https://i.ibb.co/byXm4BD/t-aoelaser-font-right.png",
  img_t_aoelaser_back: "https://i.ibb.co/KjBC7KjZ/t-aoelaser-back-right.png",
  img_t_iceray2_front: "https://i.ibb.co/Zp7Mkjgk/t-iceray2-font-right.png",
  img_t_iceray2_back: "https://i.ibb.co/1tBF9r4K/t-iceray2-back-right.png",
  img_t_miningbomb_front: "https://i.ibb.co/rGrS7VLh/t-miningbomb-front-right.png",
  img_t_tesla_front: "https://i.ibb.co/DB53cdN/t-tesla-front-right.png",
  img_t_icepuncher_front: "https://i.ibb.co/zTyyFkG9/t-icepuncher-front-right.png",
  img_t_icepuncher_back: "https://i.ibb.co/99xycgvF/t-icepuncher-back-right.png",
  img_t_densenut_front: "https://i.ibb.co/fYGyVj6Z/t-densenut-front-right.png",
  img_t_durian_front: "https://i.ibb.co/1YVCx0Kk/t-durian-front-right.png",
  img_t_spike2_front: "https://i.ibb.co/C3GxhRJV/t-spike2-front-right.png",
  img_t_holonut_front: "https://i.ibb.co/RTtm4hgj/t-holonut-front-right.png",
  img_t_minefield_front: "https://i.ibb.co/3yCjHzrL/t-minefield-front-right.png",
  img_t_minefield_unarmed: "https://i.ibb.co/fztQr2NH/t-minefield-unarmed.png",
  img_t_frostfield_front: "https://i.ibb.co/nM4tLLkJ/t-frostfield-front-right.png",
  img_t_frostfield_unarmed: "https://i.ibb.co/qwPMs0W/t-frostfield-unarmed.png",
  img_t_triberg_front: "https://i.ibb.co/CKHGSdgF/t-triberg-front-right.png",
  img_t_triberg_unarmed: "https://i.ibb.co/hF305Ym5/t-triberg-unarmed.png",

  // Block Overlays
  img_spawner_a: "https://i.ibb.co/Wv5XyQdp/blockoverlay-spawner-a.png",
  img_sun_1_a: "https://i.ibb.co/whxrPcXC/blockoverlay-sun-1-a.png",
  img_sun_1_b: "https://i.ibb.co/VYdYgK3J/blockoverlay-sun-1-b.png",
  img_sun_3_a: "https://i.ibb.co/7x2FwgLh/blockoverlay-sun-3-a.png",
  img_sun_3_b: "https://i.ibb.co/W4QvWxDW/blockoverlay-sun-3-b.png",
  img_sun_10_a: "https://i.ibb.co/G49n0S5c/blockoverlay-sun-10-a.png",
  img_tnt_a: "https://i.ibb.co/RRd6FZG/blockoverlay-tnt-a.png",
  img_seed_stray_t1: "https://i.ibb.co/NnSKj477/seed-stray-t1.png",
  img_seed_sunflower: "https://i.ibb.co/qF4r2s5Q/seed-sunflower.png",
  img_treasurechest: "https://i.ibb.co/HDnbtq3T/blockoverlay-treasurechest.png",

  // UI Icons
  img_icon_elixir: "https://i.ibb.co/yB7nHpR4/icon-elixir.png",
  img_icon_health: "https://i.ibb.co/bt6k3Z5/icon-health.png",
  img_icon_soil: "https://i.ibb.co/TBj66xWX/icon-soil.png",
  img_icon_sun: "https://i.ibb.co/vx8rqK71/icon-sun.png",

  // New Tooltip Class Icons
  img_icon_duplicate: "https://i.ibb.co/Qg4SFPS/icon-duplicate.png",
  img_icon_class_stall: "https://i.ibb.co/bjCZHjt6/icon-class-stall.png",
  img_icon_class_explode: "https://i.ibb.co/LzPJLTr2/icon-class-explode.png",
  img_icon_class_armor: "https://i.ibb.co/gZfB36HP/icon-class-armor.png",
  img_icon_class_miner: "https://i.ibb.co/HDMKj7Dr/icon-class-miner.png",
  img_icon_class_shooter: "https://i.ibb.co/jk2vm7D3/icon-class-shooter.png",

  // New Batch T1/T2 (Traps/Unarmed)
  img_t_spike_front: "https://i.ibb.co/6JLPggt9/t-spike-front-right.png",
  img_t_stun_front: "https://i.ibb.co/gMjwNPWM/t-stun-front-right.png",
  img_t_tall_front: "https://i.ibb.co/0VnYW5nz/t-tallnut-front-right.png",
  img_t_wall_front: "https://i.ibb.co/1YQ9BpsN/t-wallnut-front-right.png",
  img_t_ice_front: "https://i.ibb.co/RTKQr1Cn/t-ice-front-right.png",
  img_t_ice_unarmed: "https://i.ibb.co/spNT4j9g/t-ice-unarmed.png",
  img_t_icebomb_front: "https://i.ibb.co/3mN6BM8y/t-icebomb-front-right.png",
  img_t_icebomb_unarmed: "https://i.ibb.co/7dGQygPY/t-icebomb-unarmed.png",
  img_t_mine_front: "https://i.ibb.co/99b3MnCN/t-mine-front-right.png",
  img_t_mine_unarmed: "https://i.ibb.co/SXhVjQSD/t-mine-unarmed.png",
  img_t_minespawner_front: "https://i.ibb.co/Ndx7mb38/t-minespawner-front-right.png",
  img_t_minespawner_unarmed: "https://i.ibb.co/jPW6vVL9/t-minespawner-unarmed.png",
  img_t_pulse_front: "https://i.ibb.co/LhhTZDQm/t-pulse-front-right.png",
  img_t_stun_unarmed: "https://i.ibb.co/ccTtHHLc/t-stun-unarmed.png"
};
