
export const ASSETS = {
  img_player_front_right: "https://i.ibb.co/S4YhXH19/player-front-right.png",
  img_player_back_right: "https://i.ibb.co/SwVp44h3/player-back-right.png",
  img_armor1: "https://i.ibb.co/XZ7ZdVg3/e-armor1.png",
  img_armor2: "https://i.ibb.co/TB9Qdhkf/e-armor2.png",
  img_armor3: "https://i.ibb.co/N2dCNwFt/e-armor3.png",
  img_basic: "https://i.ibb.co/BVZB77Jg/e-basic.png",
  img_critter: "https://i.ibb.co/ksBnxyFH/e-critter.png",
  img_fast: "https://i.ibb.co/VcMYbKjp/e-fast.png",
  img_giant: "https://i.ibb.co/23cV4ct6/e-giant.png",
  img_shooting: "https://i.ibb.co/d47j3DPF/e-shooting.png",
  img_swarm_center: "https://i.ibb.co/MyKZDBGY/e-swarm-center.png",

  // Turret Assets
  img_t_firepea_front: "https://i.ibb.co/Zz2k7PCM/t-firepea-front-right.png",
  img_t_firepea_back: "https://i.ibb.co/5W4MMrxX/t-firepea-back-right.png",
  img_t_iceray_front: "https://i.ibb.co/JW2kYjJH/t-iceray-front-right.png",
  img_t_iceray_back: "https://i.ibb.co/xqJ9y2Cm/t-iceray-back-right.png",
  img_t_laser_front: "https://i.ibb.co/ccs9YWvw/t-laser-front-right.png",
  img_t_laser_back: "https://i.ibb.co/39SS0YBD/t-laser-back-right.png",
  img_t_laser2_front: "https://i.ibb.co/1fxVpc8H/t-laser2-front-right.png",
  img_t_laser2_back: "https://i.ibb.co/4RPyMPy7/t-laser2-back-right.png",
  img_t_laserexplode_front: "https://i.ibb.co/rK0052X4/t-laserexplode-front-right.png",
  img_t_laserexplode_back: "https://i.ibb.co/SDMRm4c9/t-laserexplode-back-right.png",
  img_t_mortar_front: "https://i.ibb.co/p63TyK8L/t-mortar-front-right.png",
  img_t_mortar_back: "https://i.ibb.co/svdMBgmP/t-mortar-back-right.png",
  img_t_pea_front: "https://i.ibb.co/kV7yRYjR/t-pea-front-right.png",
  img_t_pea_back: "https://i.ibb.co/sJ10NYNV/t-pea-back-right.png",
  img_t_peanut_front: "https://i.ibb.co/V0y5TJyH/t-peanut-front-right.png",
  img_t_peanut_back: "https://i.ibb.co/vCQcPgvH/t-peanut-back-right.png",
  img_t_puncher_front: "https://i.ibb.co/0jG5Ckj6/t-puncher-front-right.png",
  img_t_puncher_back: "https://i.ibb.co/F4xzmLXH/t-puncher-back-right.png",
  img_t_repeater_front: "https://i.ibb.co/7tY0xmZC/t-repeater-front-right.png",
  img_t_repeater_back: "https://i.ibb.co/9HVk6j7f/t-repeater-back-right.png",
  img_t_snowpea_front: "https://i.ibb.co/LdXZHJmY/t-snowpea-front-right.png",
  img_t_snowpea_back: "https://i.ibb.co/LzxCPC3D/t-snowpea-back-right.png",

  // New Batch
  img_t_spike_front: "https://i.ibb.co/6JLPggt9/t-spike-front-right.png",
  img_t_stun_front: "https://i.ibb.co/gMjwNPWM/t-stun-front-right.png",
  img_t_tall_front: "https://i.ibb.co/0VnYW5nz/t-tallnut-front-right.png",
  img_t_wall_front: "https://i.ibb.co/1YQ9BpsN/t-wallnut-front-right.png",
  img_t_ice_front: "https://i.ibb.co/RTKQr1Cn/t-ice-front-right.png",
  img_t_ice_unarmed: "https://i.ibb.co/spNT4j9g/t-ice-unarmed.png",
  img_t_icebomb_front: "https://i.ibb.co/3mN6BM8y/t-icebomb-front-right.png",
  img_t_icebomb_unarmed: "https://i.ibb.co/7dGQygPY/t-icebomb-unarmed.png",
  img_t_mine_front: "https://i.ibb.co/99b3MnCN/t-mine-front-right.png",
  img_t_mine_unarmed: "https://i.ibb.co/SXhVjQSD/t-mine-unarmed.png",
  img_t_minespawner_front: "https://i.ibb.co/Ndx7mb38/t-minespawner-front-right.png",
  img_t_minespawner_unarmed: "https://i.ibb.co/jPW6vVL9/t-minespawner-unarmed.png",
  img_t_pulse_front: "https://i.ibb.co/LhhTZDQm/t-pulse-front-right.png"
};
