import { GRID_SIZE, HOUR_FRAMES } from './constants';

const PURPLE_BASE = [142, 80, 200];
const PURPLE_ELITE = [100, 40, 180];
const PURPLE_GLOW = [200, 100, 255];

export const enemyTypes: any = {
  e_fast:    { cost: 10, health: 30,  speed: 1.2, size: 22, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 16 }, col: PURPLE_BASE, lootConfigOnDeath: 'e_fast' },
  e_basic:   { cost: 10, health: 60, speed: 0.5, size: 28, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8 }, col: PURPLE_BASE, lootConfigOnDeath: 'e_basic' },
  e_armor1:  { cost: 30, health: 180, speed: 0.5, size: 32, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8 }, col: PURPLE_BASE, lootConfigOnDeath: 'e_armor1', hitSfx: 'projectile_hit_hardenemy' },
  e_armor2:  { cost: 60, health: 400, speed: 0.5, size: 34, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8 }, col: PURPLE_ELITE, lootConfigOnDeath: 'e_armor2', deathSfx: 'enemy_big_death', hitSfx: 'projectile_hit_hardenemy' },
  e_armor3:  { cost: 120, health: 1000, speed: 0.5, size: 36, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8 }, col: PURPLE_ELITE, lootConfigOnDeath: 'e_armor3', deathSfx: 'enemy_big_death', hitSfx: 'projectile_hit_hardenemy' },
  e_shooting:{ cost: 45, health: 180, speed: 0.3, size: 30, actionType: ['moveDefault', 'shoot'], actionConfig: { bulletTypeKey: 'b_enemy_basic', shootRange: GRID_SIZE*4, shootFireRate: 120 }, col: PURPLE_GLOW, lootConfigOnDeath: 'e_shooting', shootSfx: 'enemy_shooting_shoot' },
  e_swarm:   { cost: 30, health: 120, speed: 0.3, size: 34, actionType: ['moveDefault', 'meleeAttack', 'spawnEnemy'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 16, enemyTypeToSpawn: ['e_critter'], spawnBudget: 8, spawnRadius: 60, spawnTriggerOnHealthRatio: [0.2, 0.1, 0], maxSpawnBudget: 24 }, col: PURPLE_GLOW, lootConfigOnDeath: 'e_swarm', deathSfx: 'enemy_swarm_death' },
  e_critter: { cost: 2,  health: 5,  speed: 0.8, size: 14, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 1, attackFireRate: 15, meleeAttackRange: 4 }, col: PURPLE_BASE, lootConfigOnDeath: 'e_critter', deathSfx: 'enemy_critter_death' },
  e_giant:   { cost: 500, health: 4000, speed: 0.4, size: 60, actionType: ['moveDefault', 'meleeAttack', 'spawnEnemy'], actionConfig: { damage: 100, attackFireRate: 60, meleeAttackRange: 24, enemyTypeToSpawn: ['e_fast'], spawnBudget: 10, spawnRadius: 80, spawnTriggerOnHealthRatio: [0.75, 0.5, 0.25], maxSpawnBudget: 30 }, col: PURPLE_ELITE, lootConfigOnDeath: 'e_giant', deathSfx: 'enemy_giant_death' },
  e_shooting_giant: { cost: 750, health: 4000, speed: 0.2, size: 60, actionType: ['moveDefault', 'shoot'], actionConfig: { bulletTypeKey: 'b_enemy_giant', shootRange: GRID_SIZE*8, shootFireRate: [6,6,6,6,6,6,6,6,6,300], inaccuracy: 10 }, col: PURPLE_ELITE, lootConfigOnDeath: 'e_shooting_giant', deathSfx: 'enemy_giant_death', shootSfx: 'enemy_shooting_shoot' },
  e_fly: { cost: 30, health: 60, speed: 0.65, size: 24, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8 }, col: PURPLE_BASE, lootConfigOnDeath: 'e_fly', isFlying: true },
  e_fly_armor1: { cost: 60, health: 180, speed: 0.65, size: 28, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8 }, col: PURPLE_BASE, lootConfigOnDeath: 'e_fly_armor1', isFlying: true, hitSfx: 'projectile_hit_hardenemy' },
  e_fly_armor2: { cost: 100, health: 400, speed: 0.65, size: 32, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8 }, col: PURPLE_BASE, lootConfigOnDeath: 'e_fly_armor2', isFlying: true, deathSfx: 'enemy_big_death', hitSfx: 'projectile_hit_hardenemy' },
  e_snowthrower: { cost: 80, health: 400, speed: 0.3, size: 30, actionType: ['moveDefault', 'shoot'], actionConfig: { bulletTypeKey: 'b_snow', shootRange: GRID_SIZE*4, shootFireRate: [15,15,15,15,15,15,15,15,15,750], inaccuracy: 15 }, col: PURPLE_BASE, lootConfigOnDeath: 'e_snowthrower' },
  e_snowthrower_giant: { cost: 1500, health: 10000, speed: 0.4, size: 60, actionType: ['moveDefault', 'shoot', 'spawnEnemy'], actionConfig: { bulletTypeKey: 'b_snow', shootRange: GRID_SIZE*8, shootFireRate: [6,6,6,6,6,6,6,60], inaccuracy: 10, enemyTypeToSpawn: ['e_icebomb'], spawnBudget: 50, spawnRadius: 200, spawnTriggerOnHealthRatio: [0.9,0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1,0.0], maxSpawnBudget: 500}, col: PURPLE_ELITE, lootConfigOnDeath: 'e_snowthrower_giant', deathSfx: 'enemy_giant_death' },
  e_bomb: { cost: 50, health: 120, speed: 0.8, size: 26, actionType: ['moveDefault', 'meleeAttack', 'spawnBullet'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8, bulletTypeToSpawn: 'b_bomb_death', spawnTriggerOnHealthRatio: [0] }, col: PURPLE_GLOW, lootConfigOnDeath: 'e_bomb', deathSfx: 'enemy_bomb_death' },
  e_poison: { cost: 50, health: 180, speed: 0.5, size: 30, actionType: ['moveDefault', 'meleeAttack', 'spawnGroundFeature'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8, groundFeatureToSpawn: 'gf_poison_gas', spawnCount: 4, spawnRadius: GRID_SIZE*3, spawnTriggerOnHealthRatio: [0] }, col: PURPLE_GLOW, lootConfigOnDeath: 'e_poison' },
  e_icebomb: { cost: 20, health: 120, speed: 0.8, size: 26, actionType: ['moveDefault', 'meleeAttack', 'spawnBullet'], actionConfig: { damage: 10, attackFireRate: 60, meleeAttackRange: 8, bulletTypeToSpawn: 'b_icebomb_death', spawnTriggerOnHealthRatio: [0] }, col: PURPLE_GLOW, lootConfigOnDeath: 'e_icebomb', deathSfx: 'enemy_bomb_death' },
  e_rockpuncher: { cost: 180, health: 1600, speed: 0.5, size: 40, actionType: ['moveDefault', 'meleeAttack', 'spawnObstacle'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 12, obstacleTypeToSpawn: 'o_stone', spawnCount: 2, spawnRadius: GRID_SIZE*3, spawnTriggerOnHealthRatio: [0] }, col: PURPLE_ELITE, lootConfigOnDeath: 'e_rockpuncher', deathSfx: 'enemy_big_death', hitSfx: 'projectile_hit_hardenemy' },
  e_suneater: { cost: 80, health: 320, speed: 0.8, size: 30, actionType: ['stealSun', 'moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8, stealRange: GRID_SIZE*6, healPerSun: 80, bypassMaxHealth: true, stealSunSpeedMultiplier: 2.0 }, col: PURPLE_GLOW, lootConfigOnDeath: 'e_suneater' },
  e_hypnotest: { cost: 0, health: 120, speed: 0.5, size: 28, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8 }, col: PURPLE_BASE, spawnWithCondition: { condition: 'c_hypnotized', duration: HOUR_FRAMES * 12 }, lootConfigOnDeath: 'e_basic' },
  e_friendly_armor2: { cost: 0, health: 400, speed: 0.65, size: 34, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8 }, col: PURPLE_ELITE, spawnWithCondition: { condition: 'c_hypnotized', duration: HOUR_FRAMES * 24 }, lootConfigOnDeath: 'e_armor2', deathSfx: 'enemy_big_death', hitSfx: 'projectile_hit_hardenemy' },
  e_fastNoDrop:{ cost: 10, health: 30, speed: 1.2, size: 22, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 16 }, col: PURPLE_BASE },
  e_launcher: { cost: 100, health: 320, speed: 0.3, size: 32, actionType: ['moveDefault', 'launchAlly'], actionConfig: { launchInterval: 360, collabRadius: GRID_SIZE * 4, maxCostToLaunch: 150, launchDistanceRatio: 0.75, launchDuration: 75, maxArcHeight: 90, prepDuration: 60 }, col: PURPLE_GLOW, lootConfigOnDeath: 'e_armor1' },
  e_leader: { cost: 100, health: 400, speed: 0.65, size: 34, actionType: ['moveDefault', 'meleeAttack', 'leadFormation'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 10, collabRadius: GRID_SIZE * 1.5, recruitRadius: GRID_SIZE * 4, maxFollowers: 4, segmentSpacing: 24 }, col: PURPLE_ELITE, lootConfigOnDeath: 'e_armor2', deathSfx: 'enemy_big_death' },
  e_frontshield: { cost: 60, health: 180, speed: 0.5, size: 32, actionType: ['moveDefault', 'meleeAttack', 'frontShield'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8, shieldHealth: 1000, shieldRadius: GRID_SIZE * 2, shieldArcDegrees: 90 }, col: PURPLE_BASE, lootConfigOnDeath: 'e_armor1', hitSfx: 'projectile_hit_hardenemy' },
  e_dummyTarget: { cost: 0, health: 50000, speed: 0, size: 60, actionType: [], actionConfig: {}, col: [150, 150, 150] },
  e_bomb_mainmenu: { cost: 50, health: 80, speed: 2.0, size: 26, actionType: ['moveDefault', 'meleeAttack', 'spawnBullet'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8, bulletTypeToSpawn: 'b_bomb_mainmenu', spawnTriggerOnHealthRatio: [0] }, col: PURPLE_GLOW, lootConfigOnDeath: 'e_bomb', deathSfx: 'enemy_bomb_death' },
  e_basic_nodrop: { cost: 10, health: 60, speed: 0.5, size: 28, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8 }, col: PURPLE_BASE },
  e_critter_nodrop: { cost: 2, health: 5, speed: 0.8, size: 14, actionType: ['moveDefault', 'meleeAttack'], actionConfig: { damage: 1, attackFireRate: 15, meleeAttackRange: 4 }, col: PURPLE_BASE, deathSfx: 'enemy_critter_death' },
  e_cloner: { cost: 40, health: 60, speed: 0.5, size: 28, actionType: ['moveDefault', 'meleeAttack', 'cloneOnDamage'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 8, cloneDistanceTiles: 2 }, col: PURPLE_GLOW, lootConfigOnDeath: 'e_basic' },
  e_swarm_chicken: { cost: 80, health: 120, speed: 0.65, size: 34, actionType: ['fleeAndHover', 'spawnCritterPeriodic'], actionConfig: { minFleeDistanceTiles: 12, maxFleeDistanceTiles: 15, spawnInterval: 90, spawnRadiusTiles: 2, panicBoostMultiplier: 3.0, panicBoostDuration: 60 }, col: PURPLE_GLOW, lootConfigOnDeath: 'e_swarm', deathSfx: 'enemy_swarm_death' },
  e_hopper: { cost: 100, health: 320, speed: 0, size: 32, actionType: ['hopJump'], actionConfig: { restFramesMin: 110, restFramesMax: 130, landingInaccuracyTiles: 0.5, landingBulletKey: 'b_hopper_slam', maxHopTiles: 3, jumpDuration: 35, maxArcHeight: 60 }, col: PURPLE_BASE, lootConfigOnDeath: 'e_armor1', hitSfx: 'projectile_hit_hardenemy' },
  e_leader_ring: { cost: 160, health: 400, speed: 0.65, size: 34, actionType: ['moveDefault', 'meleeAttack', 'leadRingFormation'], actionConfig: { damage: 10, attackFireRate: 30, meleeAttackRange: 10, collabRadius: GRID_SIZE * 1.5, recruitRadius: GRID_SIZE * 4, maxFollowers: 8, ringRadius: GRID_SIZE * 2, revolveSpeed: 0.005, healFollowerAmount: 20, healFollowerInterval: 120 }, col: PURPLE_ELITE, lootConfigOnDeath: 'e_armor2', deathSfx: 'enemy_big_death' }
};


